// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import { environment as prodEnvironment } from './environment.prod';

export const environment = {
  ...prodEnvironment,
  production: true,
  envName: 'PROD2',
  hmr: false,
  version: env.npm_package_version + '-PROD2',
  apiServerPrefix: 'https://mt2-api.prod.tsh.care',
  websocketServerPrefix: 'wss://mt2-api.prod.tsh.care',
  receiveAudio: false,
  timeStamp: env.timeStamp,
  videoProfiles: {
    instructor: { low: '480p_8', high: '720p_1' },
    participant: { low: '240p_4', high: '720p_1' }
  },
  videoCheckHelp: [
    'Please call 415-237-3040 for support.',
    'Hours are Monday - Friday<br> from 9am - 5pm Pacific time.'
  ],
  disableAv: false,
  playMusic: false,
  playMusicVolume: 20,
  networkQualityThreshold: 5, // Network quality is alerted for Agora values >= this threshold
  geoFencing: false,
  audioProfile: 'high_quality',
  defaultVolume: 100
};
