// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import { environment as prodEnvironment } from './environment.prod';

export const environment = {
  ...prodEnvironment,
  envName: 'DEV',
  production: false,
  hmr: false,
  version: env.npm_package_version + '-dev',
  apiServerPrefix: 'https://mt1-api.dev.tsh.care',
  websocketServerPrefix: 'wss://mt1-api.dev.tsh.care',
  agoraAppId: 'aa1129ec54094794a80c3d37db472e9c',
  auth0_clientId: 'KpOL3cvsqsO0d0H7Bn1M6FIQA5EHrz7K',
  auth0_domain: 'login.dev.tsh.care',
  auth0_audience: 'https://mt1-api.dev.tsh.care',
  videoProfiles: {
    instructor: { low: '480p_8', high: '720p_1' },
    participant: { low: '240p_4', high: '720p_1' }
  },
  playMusic: true,
  statsDisplay: {
    defaultForInst: true, // Are stats ON by default for the instructor?
    sampleTimeSecs: 10, // How often to we sample the stats?
    qosFilter: 2, // Consecutive QoS count to display QoS indicator
    minFps: 7,
    maxE2Etime: 150,
    maxPacketLoss: 10
  },
  // Parameters for active speaker
  activeSpeaker: {
    enabledFor: 'all', // Enabled for? 'instructor', 'all', 'none'
    sampleTimeMsec: 1000, // Sampling time in msec
    autoMute: true, // Automute lesser speakers
    maxActive: 2, // Max active spearkers if automuting
    volumeThreashold: 0.02 // Don't mute speakers below this threshold
  },
  enableGA: true,
  googleAnalyticsId: 'G-SB16EGPK4Z',
  defaultVolume: 100
};
