// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import { environment as prodEnvironment } from './environment.prod';

export const environment = {
  ...prodEnvironment,
  envName: 'TEST',
  production: false,
  hmr: false,
  version: env.npm_package_version + '-test',
  apiServerPrefix: 'https://mt1-api.test.tsh.care',
  websocketServerPrefix: 'wss://mt1-api.test.tsh.care',
  agoraAppId: 'aa1129ec54094794a80c3d37db472e9c',
  auth0_clientId: 'mzN69Zu5jQpDYdf8rzbDMCwt0l4JeBPB',
  auth0_domain: 'login.test.tsh.care',
  auth0_audience: 'https://mt1-api.test.tsh.care',
  videoProfiles: {
    instructor: { low: '480p_8', high: '480p_8' },
    participant: { low: '240p_4', high: '240p_4' }
  },
  enableGA: true,
  googleAnalyticsId: 'G-SB16EGPK4Z',
  defaultVolume: 100
};
